# Generated by Django 5.0.7 on 2024-08-10 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Collectible',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=25)),
                ('brand', models.CharField(max_length=25)),
                ('size', models.CharField(max_length=25)),
                ('player', models.CharField(max_length=25)),
                ('season', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=500)),
                ('usage_type', models.CharField(max_length=50)),
                ('for_sale', models.BooleanField()),
                ('for_trade', models.BooleanField()),
                ('asking_price', models.FloatField()),
                ('looking_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorabilia.collectible')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorabilia.collection')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.BinaryField()),
                ('game_date', models.DateField()),
                ('collectible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorabilia.collectible')),
            ],
        ),
    ]
