# Generated by Django 5.0.7 on 2024-08-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='owner_uid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='title',
            field=models.CharField(default='filler', max_length=100),
            preserve_default=False,
        ),
    ]
