# Generated by Django 5.0.7 on 2024-08-11 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0003_alter_collectible_asking_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='asking_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='for_sale',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='for_trade',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='looking_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memorabilia.collectible'),
        ),
    ]
