# Generated by Django 5.0.7 on 2024-08-21 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0004_alter_collectible_asking_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WantedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('league', models.CharField(max_length=25)),
                ('player', models.CharField(max_length=25)),
                ('season', models.CharField(blank=True, max_length=25, null=True)),
                ('description', models.CharField(max_length=500)),
                ('usage_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='collectible',
            name='looking_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memorabilia.wanteditem'),
        ),
    ]
