# Generated by Django 5.0.7 on 2024-08-24 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0005_wanteditem_alter_collectible_looking_for'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectible',
            name='game_type',
            field=models.CharField(default='', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wanteditem',
            name='game_type',
            field=models.CharField(default='gw', max_length=25),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='collectible',
            name='league',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='player',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='season',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='size',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='collectible',
            name='usage_type',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='photomatch',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.AlterField(
            model_name='wanteditem',
            name='league',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='wanteditem',
            name='player',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wanteditem',
            name='season',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='wanteditem',
            name='usage_type',
            field=models.CharField(max_length=5),
        ),
    ]
