# Generated by Django 5.0.7 on 2024-08-24 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0007_leagues'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Leagues',
            new_name='League',
        ),
    ]
