# Generated by Django 5.0.7 on 2024-08-24 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0008_rename_leagues_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='league',
            name='id',
        ),
        migrations.AddField(
            model_name='league',
            name='key',
            field=models.CharField(default=' ', max_length=5, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
