# Generated by Django 5.0.7 on 2024-08-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0010_gametype_usagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectible',
            name='game_type',
            field=models.CharField(max_length=5),
        ),
    ]
