# Generated by Django 5.0.7 on 2024-08-24 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0011_alter_collectible_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectible',
            name='image',
            field=models.ImageField(default=' ', upload_to='images'),
            preserve_default=False,
        ),
    ]
