# Generated by Django 5.0.7 on 2024-08-24 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0012_collectible_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectible',
            name='image',
        ),
        migrations.CreateModel(
            name='CollectibleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('collectible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='memorabilia.collectible')),
            ],
        ),
    ]
