# Generated by Django 5.0.7 on 2024-09-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0013_remove_collectible_image_collectibleimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleimage',
            name='primary',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
