# Generated by Django 5.0.7 on 2024-09-15 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0014_collectibleimage_primary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photomatch',
            name='collectible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photomatches', to='memorabilia.collectible'),
        ),
    ]
