# Generated by Django 5.0.7 on 2024-09-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0015_alter_photomatch_collectible'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
            preserve_default=False,
        ),
    ]
