# Generated by Django 5.0.7 on 2024-09-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0016_collection_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='image_link',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
