# Generated by Django 5.0.7 on 2024-09-21 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0017_collection_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='image_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
