# Generated by Django 5.0.7 on 2024-09-29 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0018_alter_collection_image_alter_collection_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectible',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
