# Generated by Django 5.0.7 on 2024-12-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0019_collectible_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleimage',
            name='flickrObject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collectibleimage',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='collectibleimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
