# Generated by Django 5.0.7 on 2025-03-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0020_collectibleimage_flickrobject_collectibleimage_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomatch',
            name='description',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='photomatch',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='photomatch',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
