# Generated by Django 5.0.7 on 2025-03-13 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0021_photomatch_description_photomatch_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectible',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='collection',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
