# Generated by Django 5.2.5 on 2025-08-16 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0023_externalresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectible',
            name='team',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
