# Generated by Django 5.2.5 on 2025-08-16 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0024_collectible_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorabilia.league')),
            ],
            options={
                'unique_together': {('name', 'league')},
            },
        ),
    ]
