# Generated by Django 5.2.5 on 2025-10-05 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0025_team'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Collectible',
            new_name='PlayerItem',
        ),
        migrations.RenameModel(
            old_name='CollectibleImage',
            new_name='PlayerItemImage',
        ),
    ]
