# Generated by Django 5.2.5 on 2025-10-11 18:29

import django.db.models.deletion
import django.utils.timezone
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0026_rename_collectible_playeritem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('for_sale', models.BooleanField(blank=True, null=True)),
                ('for_trade', models.BooleanField(blank=True, null=True)),
                ('asking_price', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorabilia.collection')),
                ('looking_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memorabilia.wanteditem')),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='OtherItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('flickrObject', models.TextField(blank=True, null=True)),
                ('collectible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='memorabilia.otheritem')),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
    ]
