# Generated by Django 5.2.5 on 2026-03-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0030_playeritem_playeritemimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='otheritem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playergearitem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='playeritem',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
