# Generated by Django 5.2.5 on 2026-03-12 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0031_last_updated_auto_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playergearitem',
            name='game_type',
            field=models.ForeignKey(db_column='game_type', on_delete=django.db.models.deletion.PROTECT, to='memorabilia.gametype'),
        ),
        migrations.AlterField(
            model_name='playergearitem',
            name='usage_type',
            field=models.ForeignKey(db_column='usage_type', on_delete=django.db.models.deletion.PROTECT, to='memorabilia.usagetype'),
        ),
    ]
