# Generated by Django 5.2.5 on 2026-03-16 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0033_flickrobject_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='collage_collectible_ids',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
