# Generated by Django 5.2.5 on 2026-03-22 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0035_performance_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowObtainedOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoaType',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='otheritem',
            name='how_obtained',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playergearitem',
            name='how_obtained',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playeritem',
            name='how_obtained',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='otheritem',
            name='loa',
            field=models.ForeignKey(blank=True, db_column='loa', null=True, on_delete=django.db.models.deletion.PROTECT, to='memorabilia.loatype'),
        ),
        migrations.AddField(
            model_name='playergearitem',
            name='loa',
            field=models.ForeignKey(blank=True, db_column='loa', null=True, on_delete=django.db.models.deletion.PROTECT, to='memorabilia.loatype'),
        ),
        migrations.AddField(
            model_name='playeritem',
            name='loa',
            field=models.ForeignKey(blank=True, db_column='loa', null=True, on_delete=django.db.models.deletion.PROTECT, to='memorabilia.loatype'),
        ),
    ]
