# Generated by Django 5.2.5 on 2026-03-22 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0036_howobtainedoption_loatype_otheritem_how_obtained_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OtherItem',
            new_name='GeneralItem',
        ),
        migrations.RenameModel(
            old_name='OtherItemImage',
            new_name='GeneralItemImage',
        ),
        migrations.RenameIndex(
            model_name='generalitem',
            new_name='mem_generalitem_updated_idx',
            old_name='mem_otheritem_updated_idx',
        ),
    ]
