# Generated by Django 5.2.5 on 2026-03-22 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0040_update_collage_playergearitem_to_playergear'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearType',
            fields=[
                ('key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='playergear',
            name='gear_type',
            field=models.ForeignKey(blank=True, db_column='gear_type', null=True, on_delete=django.db.models.deletion.PROTECT, to='memorabilia.geartype'),
        ),
    ]
