# Generated by Django 5.2.5 on 2026-03-22 20:03

import django.db.models.deletion
import rules.contrib.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0041_add_geartype_and_gear_type_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeasonSet',
            fields=[
                ('key', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HockeyJersey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('for_sale', models.BooleanField(blank=True, null=True)),
                ('for_trade', models.BooleanField(blank=True, null=True)),
                ('asking_price', models.FloatField(blank=True, null=True)),
                ('how_obtained', models.CharField(blank=True, max_length=255, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('league', models.CharField(blank=True, max_length=5, null=True)),
                ('player', models.CharField(max_length=100)),
                ('team', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('brand', models.CharField(max_length=25)),
                ('size', models.CharField(max_length=5)),
                ('season', models.CharField(max_length=10)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorabilia.collection')),
                ('game_type', models.ForeignKey(db_column='game_type', on_delete=django.db.models.deletion.PROTECT, to='memorabilia.gametype')),
                ('gear_type', models.ForeignKey(blank=True, db_column='gear_type', null=True, on_delete=django.db.models.deletion.PROTECT, to='memorabilia.geartype')),
                ('loa', models.ForeignKey(blank=True, db_column='loa', null=True, on_delete=django.db.models.deletion.PROTECT, to='memorabilia.loatype')),
                ('looking_for', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memorabilia.wanteditem')),
                ('usage_type', models.ForeignKey(db_column='usage_type', on_delete=django.db.models.deletion.PROTECT, to='memorabilia.usagetype')),
                ('season_set', models.ForeignKey(blank=True, db_column='season_set', null=True, on_delete=django.db.models.deletion.PROTECT, to='memorabilia.seasonset')),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HockeyJerseyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary', models.BooleanField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('flickrObject', models.JSONField(blank=True, null=True)),
                ('collectible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gear_images', to='memorabilia.hockeyjersey')),
            ],
            options={
                'abstract': False,
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='hockeyjersey',
            index=models.Index(fields=['last_updated'], name='mem_hockeyjersey_updated_idx'),
        ),
    ]
