# Generated by Django 5.2.5 on 2026-03-23 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0045_hockeyjersey_to_proxy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalitem',
            name='coa',
            field=models.ForeignKey(blank=True, db_column='coa', null=True, on_delete=django.db.models.deletion.PROTECT, to='memorabilia.coatype'),
        ),
        migrations.AlterField(
            model_name='playergear',
            name='coa',
            field=models.ForeignKey(blank=True, db_column='coa', null=True, on_delete=django.db.models.deletion.PROTECT, to='memorabilia.coatype'),
        ),
        migrations.AlterField(
            model_name='playergear',
            name='season_set',
            field=models.ForeignKey(blank=True, db_column='season_set', null=True, on_delete=django.db.models.deletion.PROTECT, to='memorabilia.seasonset'),
        ),
        migrations.AlterField(
            model_name='playeritem',
            name='coa',
            field=models.ForeignKey(blank=True, db_column='coa', null=True, on_delete=django.db.models.deletion.PROTECT, to='memorabilia.coatype'),
        ),
    ]
