# Generated by Django 5.2.5 on 2026-04-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0048_collectible_flickr_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='allow_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generalitem',
            name='allow_featured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playergear',
            name='allow_featured',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playeritem',
            name='allow_featured',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
