# Generated by Django 5.2.5 on 2026-04-11 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0049_collection_allow_featured_generalitem_allow_featured_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playergear',
            name='home_away',
            field=models.CharField(blank=True, choices=[('H', 'Home'), ('A', 'Away')], max_length=1, null=True),
        ),
    ]
