# Generated by Django 5.2.5 on 2026-04-19 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0051_export_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthSource',
            fields=[
                ('key', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='playergear',
            name='auth_tag_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='playergear',
            name='team_inventory_number',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
        migrations.AddField(
            model_name='playergear',
            name='auth_source',
            field=models.ForeignKey(blank=True, db_column='auth_source', null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorabilia.authsource'),
        ),
    ]
