# Generated by Django 5.2.5 on 2026-04-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0052_authsource_playergear_auth_tag_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authsource',
            options={'ordering': ['name']},
        ),
    ]
