# Generated by Django 5.2.5 on 2026-04-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0053_alter_authsource_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeiGrayEntry',
            fields=[
                ('tag_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=150)),
                ('player', models.CharField(max_length=100)),
                ('jersey_number', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(max_length=255)),
                ('set_number', models.CharField(max_length=20)),
                ('size', models.CharField(blank=True, max_length=10)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('games_worn', models.JSONField(default=list)),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
