# Generated by Django 5.2.5 on 2026-04-19 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0054_meigrayentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopulationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.CharField(max_length=10, unique=True)),
                ('file', models.FileField(upload_to='population_reports/')),
                ('imported_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='meigrayentry',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorabilia.populationreport'),
        ),
    ]
