# Generated by Django 5.2.5 on 2026-04-22 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0058_remove_old_auth_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomatch',
            name='getty_embed_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
