# Generated by Django 5.2.5 on 2026-04-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0059_photomatch_getty_embed_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomatch',
            name='getty_embed_url',
        ),
        migrations.AddField(
            model_name='photomatch',
            name='getty_embed_code',
            field=models.TextField(blank=True, null=True),
        ),
    ]
