# Generated by Django 5.2.5 on 2026-04-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0060_remove_photomatch_getty_embed_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photomatch',
            name='getty_thumbnail_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
