# Generated by Django 5.2.5 on 2026-04-26 16:46

import django.db.models.deletion
import rules.contrib.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0061_photomatch_getty_thumbnail_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WantList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WantListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collectible_type', models.CharField(choices=[('playeritem', 'Player Item'), ('playergear', 'Player Gear'), ('hockeyjersey', 'Hockey Jersey'), ('generalitem', 'General Item')], max_length=15)),
                ('player', models.CharField(blank=True, max_length=100, null=True)),
                ('team', models.CharField(blank=True, max_length=150, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('season', models.CharField(blank=True, max_length=10, null=True)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('game_type', models.ForeignKey(blank=True, db_column='game_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorabilia.gametype')),
                ('gear_type', models.ForeignKey(blank=True, db_column='gear_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorabilia.geartype')),
                ('league', models.ForeignKey(blank=True, db_column='league', null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorabilia.league')),
                ('season_set', models.ForeignKey(blank=True, db_column='season_set', null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorabilia.seasonset')),
                ('usage_type', models.ForeignKey(blank=True, db_column='usage_type', null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorabilia.usagetype')),
                ('want_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='memorabilia.wantlist')),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='WantListItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('link', models.CharField(blank=True, max_length=255, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='memorabilia.wantlistitem')),
            ],
        ),
        migrations.CreateModel(
            name='WantListProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('header_image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('header_image_link', models.CharField(blank=True, max_length=255, null=True)),
                ('visibility', models.CharField(choices=[('public', 'Public'), ('logged_in', 'Logged-in users only'), ('private', 'Private')], default='public', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='want_list_profile', to=settings.AUTH_USER_MODEL)),
            ],
            bases=(rules.contrib.models.RulesModelMixin, models.Model),
        ),
        migrations.AddField(
            model_name='wantlist',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='want_lists', to='memorabilia.wantlistprofile'),
        ),
    ]
