# Generated by Django 5.2.5 on 2026-04-26 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0062_wantlist_wantlistitem_wantlistitemimage_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wantlistitem',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='wantlistitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
