# Generated by Django 6.0.5 on 2026-05-25 02:42

import django.db.models.deletion
import uuid6
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0063_alter_wantlistitem_options_wantlistitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='populationreport',
            name='league',
            field=models.CharField(default='NHL', max_length=10),
        ),
        migrations.AlterField(
            model_name='populationreport',
            name='season',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='populationreport',
            unique_together={('season', 'league')},
        ),
        migrations.CreateModel(
            name='MeiGrayScheduleEntry',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False, unique=True)),
                ('season', models.CharField(max_length=10)),
                ('league', models.CharField(default='NHL', max_length=10)),
                ('team', models.CharField(max_length=150)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memorabilia.populationreport')),
            ],
            options={
                'ordering': ['team', 'season'],
            },
        ),
        migrations.CreateModel(
            name='MeiGrayScheduleGameEntry',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('opponent', models.CharField(max_length=100)),
                ('game_date', models.DateField(db_index=True)),
                ('jersey', models.CharField(blank=True, max_length=100)),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('home_game', models.BooleanField(default=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='memorabilia.meigrayscheduleentry')),
            ],
            options={
                'ordering': ['game_date'],
            },
        ),
        migrations.CreateModel(
            name='MeiGrayScheduleSetEntry',
            fields=[
                ('id', models.UUIDField(default=uuid6.uuid7, editable=False, primary_key=True, serialize=False)),
                ('set_label', models.CharField(max_length=50)),
                ('lane', models.CharField(blank=True, max_length=20)),
                ('set_number', models.CharField(blank=True, max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('game_count', models.PositiveIntegerField(blank=True, null=True)),
                ('raw_value', models.CharField(blank=True, max_length=255)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='set_ranges', to='memorabilia.meigrayscheduleentry')),
            ],
            options={
                'ordering': ['set_label'],
            },
        ),
        migrations.CreateModel(
            name='MeiGrayTagEntry',
            fields=[
                ('season', models.CharField(max_length=10)),
                ('league', models.CharField(max_length=5)),
                ('tag_number', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('team', models.CharField(max_length=150)),
                ('player', models.CharField(max_length=100)),
                ('jersey_number', models.CharField(blank=True, max_length=10)),
                ('color', models.CharField(max_length=255)),
                ('set_number', models.CharField(max_length=20)),
                ('size', models.CharField(blank=True, max_length=10)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('imported_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memorabilia.populationreport')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='memorabilia.meigrayscheduleentry')),
            ],
        ),
        migrations.DeleteModel(
            name='MeiGrayEntry',
        ),
        migrations.AddIndex(
            model_name='meigrayscheduleentry',
            index=models.Index(fields=['team', 'season'], name='idx_schedule_team_season'),
        ),
        migrations.AddConstraint(
            model_name='meigrayscheduleentry',
            constraint=models.UniqueConstraint(fields=('team', 'season', 'league'), name='uq_schedule_team_season_league'),
        ),
        migrations.AddIndex(
            model_name='meigrayschedulegameentry',
            index=models.Index(fields=['schedule', 'game_date'], name='idx_game_schedule_date'),
        ),
        migrations.AddIndex(
            model_name='meigrayschedulegameentry',
            index=models.Index(fields=['opponent', 'game_date'], name='idx_game_opponent_date'),
        ),
        migrations.AddConstraint(
            model_name='meigrayschedulegameentry',
            constraint=models.UniqueConstraint(fields=('schedule', 'game_date', 'opponent'), name='uq_game_schedule_date_opponent'),
        ),
        migrations.AddIndex(
            model_name='meigraytagentry',
            index=models.Index(fields=['schedule'], name='idx_item_schedule'),
        ),
    ]
