# Generated by Django 6.0.5 on 2026-05-08 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0063_alter_wantlistitem_options_wantlistitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='meigrayentry',
            name='league',
            field=models.CharField(default='NHL', max_length=10),
        ),
        migrations.AddField(
            model_name='populationreport',
            name='league',
            field=models.CharField(default='NHL', max_length=10),
        ),
        migrations.AlterField(
            model_name='populationreport',
            name='season',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='populationreport',
            unique_together={('season', 'league')},
        ),
    ]
