# Generated by Django 6.0.5 on 2026-05-08 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0064_meigrayentry_league_populationreport_league_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meigrayentry',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='memorabilia.populationreport'),
        ),
    ]
