# Generated by Django 6.0.5 on 2026-05-25 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0065_alter_meigraytagentry_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='meigrayschedulegameentry',
            name='game_type',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
