# Generated by Django 6.0.5 on 2026-05-18 00:51

import memorabilia.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0065_alter_meigrayentry_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meigrayentry',
            name='notes',
            field=models.JSONField(blank=True, default=memorabilia.models.default_meigray_notes),
        ),
    ]
