# Generated by Django 6.0.5 on 2026-05-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0066_meigrayschedulegameentry_game_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meigraytagentry',
            name='tag_number',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
