# Generated by Django 6.0.5 on 2026-05-25 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0067_alter_meigraytagentry_tag_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meigrayschedulesetentry',
            old_name='raw_value',
            new_name='dates',
        ),
        migrations.RemoveField(
            model_name='meigrayschedulesetentry',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='meigrayschedulesetentry',
            name='lane',
        ),
        migrations.RemoveField(
            model_name='meigrayschedulesetentry',
            name='set_number',
        ),
        migrations.RemoveField(
            model_name='meigrayschedulesetentry',
            name='start_date',
        ),
        migrations.AlterField(
            model_name='meigraytagentry',
            name='set_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
