# Generated by Django 6.0.5 on 2026-05-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0068_rename_raw_value_meigrayschedulesetentry_dates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meigrayschedulesetentry',
            name='game_count',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
