# Generated by Django 6.0.5 on 2026-05-26 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0069_alter_meigrayschedulesetentry_game_count'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PopulationReport',
            new_name='MeiGrayPopulationReport',
        ),
    ]
