# Generated by Django 6.0.5 on 2026-05-30 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0070_rename_populationreport_meigraypopulationreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meigraytagentry',
            name='size',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='meigraytagentry',
            name='tag_number',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
