# Generated by Django 6.0.5 on 2026-06-07 18:14

import django.db.models.deletion
import memorabilia.models
from django.db import migrations, models


def _assign_unique_tokens(apps, schema_editor):
    """Give every existing inquiry a distinct token before the unique
    constraint is applied (the callable default would otherwise stamp them all
    with the same value)."""
    OwnerInquiry = apps.get_model('memorabilia', 'OwnerInquiry')
    for inquiry in OwnerInquiry.objects.all():
        inquiry.token = memorabilia.models._generate_inquiry_token()
        inquiry.save(update_fields=['token'])


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0073_ownerinquiry_sender_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownerinquiry',
            name='email_sent',
        ),
        migrations.RemoveField(
            model_name='ownerinquiry',
            name='message',
        ),
        migrations.AddField(
            model_name='ownerinquiry',
            name='item_url',
            field=models.CharField(blank=True, max_length=255),
        ),
        # Add the token non-unique, populate distinct values, then enforce uniqueness.
        migrations.AddField(
            model_name='ownerinquiry',
            name='token',
            field=models.CharField(default=memorabilia.models._generate_inquiry_token, editable=False, max_length=32),
        ),
        migrations.RunPython(_assign_unique_tokens, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='ownerinquiry',
            name='token',
            field=models.CharField(default=memorabilia.models._generate_inquiry_token, editable=False, max_length=32, unique=True),
        ),
        migrations.CreateModel(
            name='InquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('requester', 'Requester'), ('owner', 'Owner')], max_length=10)),
                ('body', models.TextField(max_length=2000)),
                ('inbound', models.BooleanField(default=False)),
                ('email_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='memorabilia.ownerinquiry')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
