# Generated by Django 6.0.5 on 2026-06-20 18:38

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def backfill_wantlist_slugs(apps, schema_editor):
    """Give existing want lists a slug (unique per profile) before the unique
    constraint is applied."""
    WantList = apps.get_model('memorabilia', 'WantList')
    used_by_profile = {}
    for wl in WantList.objects.all().order_by('profile_id', 'order', 'id'):
        used = used_by_profile.setdefault(wl.profile_id, set())
        base = slugify(wl.title) or 'list'
        slug = base
        n = 1
        while slug in used:
            slug = f'{base}-{n}'
            n += 1
        used.add(slug)
        wl.slug = slug
        wl.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0074_remove_ownerinquiry_email_sent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalitem',
            name='trade_want_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memorabilia.wantlist'),
        ),
        migrations.AddField(
            model_name='playergear',
            name='trade_want_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memorabilia.wantlist'),
        ),
        migrations.AddField(
            model_name='playeritem',
            name='trade_want_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='memorabilia.wantlist'),
        ),
        migrations.AddField(
            model_name='wantlist',
            name='slug',
            field=models.SlugField(blank=True, max_length=60),
        ),
        migrations.RunPython(backfill_wantlist_slugs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='wantlist',
            constraint=models.UniqueConstraint(fields=('profile', 'slug'), name='uniq_wantlist_slug_per_profile'),
        ),
    ]
