# Generated by Django 6.0.5 on 2026-06-21 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0075_generalitem_trade_want_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerinquiry',
            name='interest',
            field=models.CharField(blank=True, choices=[('sale', 'For sale'), ('trade', 'For trade')], max_length=5),
        ),
        migrations.AddField(
            model_name='ownerinquiry',
            name='item_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
