# Generated by Django 6.0.5 on 2026-06-21 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0076_ownerinquiry_interest_ownerinquiry_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD – US Dollar'), ('CAD', 'CAD – Canadian Dollar'), ('EUR', 'EUR – Euro'), ('GBP', 'GBP – British Pound'), ('AUD', 'AUD – Australian Dollar'), ('CHF', 'CHF – Swiss Franc'), ('SEK', 'SEK – Swedish Krona'), ('CZK', 'CZK – Czech Koruna'), ('JPY', 'JPY – Japanese Yen')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='ownerinquiry',
            name='item_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='playergear',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD – US Dollar'), ('CAD', 'CAD – Canadian Dollar'), ('EUR', 'EUR – Euro'), ('GBP', 'GBP – British Pound'), ('AUD', 'AUD – Australian Dollar'), ('CHF', 'CHF – Swiss Franc'), ('SEK', 'SEK – Swedish Krona'), ('CZK', 'CZK – Czech Koruna'), ('JPY', 'JPY – Japanese Yen')], default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='playeritem',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD – US Dollar'), ('CAD', 'CAD – Canadian Dollar'), ('EUR', 'EUR – Euro'), ('GBP', 'GBP – British Pound'), ('AUD', 'AUD – Australian Dollar'), ('CHF', 'CHF – Swiss Franc'), ('SEK', 'SEK – Swedish Krona'), ('CZK', 'CZK – Czech Koruna'), ('JPY', 'JPY – Japanese Yen')], default='USD', max_length=3),
        ),
    ]
