# Generated by Django 6.0.5 on 2026-08-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorabilia', '0077_generalitem_currency_ownerinquiry_item_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalitem',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD – US Dollar'), ('CAD', 'CAD – Canadian Dollar'), ('EUR', 'EUR – Euro'), ('GBP', 'GBP – British Pound'), ('AUD', 'AUD – Australian Dollar'), ('NZD', 'NZD – New Zealand Dollar'), ('MXN', 'MXN – Mexican Peso')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='playergear',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD – US Dollar'), ('CAD', 'CAD – Canadian Dollar'), ('EUR', 'EUR – Euro'), ('GBP', 'GBP – British Pound'), ('AUD', 'AUD – Australian Dollar'), ('NZD', 'NZD – New Zealand Dollar'), ('MXN', 'MXN – Mexican Peso')], default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='playeritem',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD – US Dollar'), ('CAD', 'CAD – Canadian Dollar'), ('EUR', 'EUR – Euro'), ('GBP', 'GBP – British Pound'), ('AUD', 'AUD – Australian Dollar'), ('NZD', 'NZD – New Zealand Dollar'), ('MXN', 'MXN – Mexican Peso')], default='USD', max_length=3),
        ),
    ]
