from django.urls import path, include
from . import views

app_name = "memorabilia"
urlpatterns = [
    path("", views.home, name="home"),
    path("search", views.search_collectibles, name="search_collectibles"),
    path('accounts/', include('allauth.urls')),
    path("collection/create", views.create_collection, name="create_collection"),
    path("collection/", views.IndexView.as_view(), name="list_collections"),
    path("collection/mine/", views.MyCollectionsView.as_view(), name="my_collections"),
    path("collection/user/<str:username>/", views.UserCollectionsView.as_view(), name="user_collections"),
    path("collection/<int:pk>/", views.CollectionView.as_view(), name="collection"),
    path("collection/<int:collection_id>/edit", views.edit_collection, name="edit_collection"),
    path("collection/<int:collection_id>/delete", views.delete_collection, name="delete_collection"),
    path("collection/<int:collection_id>/collectible/create", views.create_collectible, name="create_collectible"),
    path("collection/<int:collection_id>/collectible/<str:collectible_type>/<int:pk>", views.CollectibleView.as_view(), name="collectible"),
    path("collection/<int:collection_id>/collectible/<str:collectible_type>/<int:pk>/pdf", views.collectible_pdf, name="collectible_pdf"),
    path("collection/<int:collection_id>/collectible/<str:collectible_type>/<int:collectible_id>/edit", views.edit_collectible, name="edit_collectible"),
    path("collection/<int:collection_id>/collectible/<str:collectible_type>/<int:collectible_id>/delete", views.delete_collectible, name="delete_collectible"),
    path("collection/<int:collection_id>/bulk-edit", views.bulk_edit_collectibles, name="bulk_edit_collectibles"),
    path("collection/<int:collection_id>/collectible/<str:collectible_type>/<int:collectible_id>/photoMatch/create", views.create_photo_match, name="create_photo_match"),
    path("collection/<int:collection_id>/collectible/<str:collectible_type>/<int:collectible_id>/photoMatch/<int:pk>", views.PhotoMatchView.as_view(), name="photo_match"),
    path("collection/<int:collection_id>/collectible/<str:collectible_type>/<int:collectible_id>/photoMatch/<int:photo_match_id>/edit", views.edit_photo_match, name="edit_photo_match"),
    path("collection/<int:collection_id>/collectible/<str:collectible_type>/<int:collectible_id>/photoMatch/<int:photo_match_id>/delete", views.delete_photo_match, name="delete_photo_match"),
    path("external/flickr/album", views.get_flickr_album, name="get_flickr_album"),
    path("external/flickr/albums/<str:username>/<str:album>", views.get_flickr_albums, name="get_flickr_albums"),
    path("external/flickr/user-albums", views.get_flickr_user_albums, name="get_flickr_user_albums"),
    path("external/flickr/album-photo-ids", views.get_flickr_album_photo_ids, name="get_flickr_album_photo_ids"),
    path("collection/<int:collection_id>/bulk-add-flickr", views.bulk_add_from_flickr, name="bulk_add_from_flickr"),
    path("collection/<int:collection_id>/bulk-add-flickr/album", views.bulk_add_flickr_album, name="bulk_add_flickr_album"),
    path("collection/<int:collection_id>/bulk-add-flickr/batch", views.bulk_add_flickr_batch, name="bulk_add_flickr_batch"),
    path("profile/", views.profile, name="profile"),
    path("resources", views.ExternalResourceListView.as_view(), name="list_externalresources"),
    path("api/teams", views.get_teams, name="get_teams"),
    # Export
    path("collection/<int:collection_id>/export", views.export_collection, name="export_collection"),
    path("collection/<int:collection_id>/collectible/<str:collectible_type>/<int:collectible_id>/export", views.export_collectible, name="export_collectible"),
    # Population Reports
    path("population-report/<str:season>/download", views.download_population_report, name="download_population_report"),
    # Import
    path("import/", views.import_upload, name="import_upload"),
    path("import/preview/", views.import_preview, name="import_preview"),
    path("collection/<int:collection_id>/import/", views.import_upload, name="collection_import"),
    # Want Lists — management paths must precede the public <slug> catch-all
    path("wants/manage/", views.want_list_manage, name="want_list_manage"),
    path("wants/manage/profile/", views.want_list_profile_edit, name="want_list_profile_edit"),
    path("wants/manage/lists/create/", views.want_list_create, name="want_list_create"),
    path("wants/manage/lists/reorder/", views.want_list_reorder, name="want_list_reorder"),
    path("wants/manage/lists/<int:pk>/edit/", views.want_list_edit, name="want_list_edit"),
    path("wants/manage/lists/<int:pk>/delete/", views.want_list_delete, name="want_list_delete"),
    path("wants/manage/lists/<int:list_pk>/items/add/", views.want_list_item_create, name="want_list_item_create"),
    path("wants/manage/items/reorder/", views.want_list_item_reorder, name="want_list_item_reorder"),
    path("wants/manage/items/<int:pk>/edit/", views.want_list_item_edit, name="want_list_item_edit"),
    path("wants/manage/items/<int:pk>/delete/", views.want_list_item_delete, name="want_list_item_delete"),
    path("wants/manage/items/<int:pk>/convert/", views.want_list_item_convert, name="want_list_item_convert"),
    path("wants/manage/export/", views.want_list_export, name="want_list_export"),
    path("wants/manage/import/", views.want_list_import, name="want_list_import"),
    path("wants/<slug:slug>/", views.want_list_public, name="want_list_public"),
]
