name: Sync uat with main

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  sync:
    if: github.event.pull_request.merged == true
    uses: wittjr/workflows/.github/workflows/sync-uat-with-main.yml@main
    secrets:
      SYNC_PAT: ${{ secrets.SYNC_PAT }}